version: "3.8"
services:
  server:
    image: "nginx:1.19.10-alpine"
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3001:80"
    depends_on: 
      - php
      - mysql
  php:
    build: 
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./backend:/var/www/html
  mysql:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    env_file: ./mysql.env
  node:
    image: "node:16-alpine"
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: "npm run dev"
    environment:
      HOST: 0.0.0.0
  npm:
    image: "node:16-alpine"
    working_dir: /app
    volumes:
      - ./backend:/app
    entrypoint: "npm"
  composer:
    image: "composer"
    volumes:
      - ./backend:/app
    entrypoint: "composer --ignore-platform-reqs"
  artisan:
    build: 
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./backend:/var/www/html
    entrypoint: "php artisan"
